sudo: required
services:
	- docker
	
before_install:
	- docker build -t <TAG/docker-react> -f Dockerfile.dev .
	
script:
	- docker run (NAME_IMAGE/docker-react npm run test -- --coverage

deploy:
	provider: elasticbeanstalk
	region: <Paste_the_region_indicate_in_AWS_URL:"us-west-2">
	app: "docker"
	env: <Paste_the_environnement_name_indicate_in_AWS:"Docker-env">
	bucket_name: <Paste_the_S3_bucket_indicate_in_AWS:"xxx">
	bucket_path: <exactly the same name as app name>"docker"
	on:
		branch: master
	access_key_id: $AWS_ACCESS_KEY
	secret_access_key: 
		secure: "$AWS_SECRET_KEY"